# Generated by Django 6.0.7 on 2026-08-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="company",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="education",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="github",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="linkedin",
            field=models.URLField(blank=True, default=""),
        ),
    ]
